name: Check Lesson 02 Pull Request

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - "lesson_02/quiz_python/**"
      - "lib/python/**"

jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install codedifferently_instructional package
        run: |
          python -m pip install --upgrade pip
          pip install -e lib/python

      - name: Install lesson dependencies
        working-directory: ./lesson_02/quiz_python
        run: |
          pip install -r requirements.txt

      - name: Run pytest
        working-directory: ./lesson_02/quiz_python
        run: pytest

    # Python representation to be done when codedifferently-instructional is updated to support Python. For now, we can ignore this step.
    # - name: Build Shared Lib with Node.js
    #   working-directory: ./lib/javascript/codedifferently-instructional
    #   run: npm ci
